{
  "openapi": "3.0.1",
  "info": {
    "title": "API V1",
    "version": "v1",
    "description": "Rswag Blog API"
  },
  "servers": [
    {
      "url": "http://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "localhost:3000"
        }
      }
    }
  ],
  "paths": {
    "/api/v1/categories/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "id",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "show category",
        "responses": {
          "200": {
            "description": "successful",
            "content": {
              "application/json": {
                "example": {
                  "category": {
                    "id": 4,
                    "name": "Schimmel-Braun",
                    "created_at": "2022-01-24T15:18:06.683Z",
                    "updated_at": "2022-01-24T15:18:06.683Z"
                  },
                  "articles": [
                    {
                      "id": 13,
                      "title": "10 причин чому ваша дитина погано спить",
                      "description": "Щоб ваша дитина виросла здоровою і добре розвивалася,\n    привчайте її до певного розпорядку дня. Регулярне годування – основа режиму\n    немовляти. Годуйте новонародженого до 3-х місяців (включно) сім разів на добу\n    через 3 години. Після 3-х місячного віку переходьте на годування через 3,5\n    години (6 разів) з перервою вночі 6,5 годин. З 5-6-ти місячного віку годуєте\n    дитину п’ять разів на день через 4 години, з перервою на ніч – 8 годин.\n    Після ситного обіду новонароджена дитина має не спати близько півгодини,\n    двомісячна – близько години. Для сну дитині потрібне свіже і прохолодне\n    повітря, тому необхідно провітрювати його кімнату.\n    З трьохмісячного, до десятимісячного віку малюк повинен спати по 2 години\n    три рази на день, а з 10 місяців і до року – по 2-2,5 години два рази на\n    день.\n    Крім провітрювання, дитині необхідні свіже повітря і сонячне світло.\n    Вона повинна проводити на свіжому повітрі декілька годин, і поки вона не\n    може ходити, укладайте її спати вдень на свіжому повітрі – це зміцнить її\n    організм і застереже від захворювань .\n    Прогулянки починайте з двотижневого віку протягом 15-20 хвилин, поступово\n    подовжуючи час прогулянок до 1,5-2 годин.",
                      "published_at": "2022-01-24T15:28:06.713Z",
                      "created_at": "2022-01-24T15:18:06.718Z",
                      "updated_at": "2022-01-24T15:18:06.718Z",
                      "image": {
                        "url": "/uploads/article/image/13/2.png"
                      },
                      "category_id": 4,
                      "age": "4-5 роки",
                      "subject": "Вакцинація"
                    },
                    {
                      "id": 14,
                      "title": "Як виробити режим сну у дитини",
                      "description": "Щоб ваша дитина виросла здоровою і добре розвивалася,\n    привчайте її до певного розпорядку дня. Регулярне годування – основа режиму\n    немовляти. Годуйте новонародженого до 3-х місяців (включно) сім разів на добу\n    через 3 години. Після 3-х місячного віку переходьте на годування через 3,5\n    години (6 разів) з перервою вночі 6,5 годин. З 5-6-ти місячного віку годуєте\n    дитину п’ять разів на день через 4 години, з перервою на ніч – 8 годин.\n    Після ситного обіду новонароджена дитина має не спати близько півгодини,\n    двомісячна – близько години. Для сну дитині потрібне свіже і прохолодне\n    повітря, тому необхідно провітрювати його кімнату.\n    З трьохмісячного, до десятимісячного віку малюк повинен спати по 2 години\n    три рази на день, а з 10 місяців і до року – по 2-2,5 години два рази на\n    день.\n    Крім провітрювання, дитині необхідні свіже повітря і сонячне світло.\n    Вона повинна проводити на свіжому повітрі декілька годин, і поки вона не\n    може ходити, укладайте її спати вдень на свіжому повітрі – це зміцнить її\n    організм і застереже від захворювань .\n    Прогулянки починайте з двотижневого віку протягом 15-20 хвилин, поступово\n    подовжуючи час прогулянок до 1,5-2 годин.",
                      "published_at": "2022-01-24T15:28:06.762Z",
                      "created_at": "2022-01-24T15:18:06.768Z",
                      "updated_at": "2022-01-24T15:18:06.768Z",
                      "image": {
                        "url": "/uploads/article/image/14/2.png"
                      },
                      "category_id": 4,
                      "age": "12-18 місяців",
                      "subject": "Підгузок"
                    },
                    {
                      "id": 15,
                      "title": "Як зрозуміти що ваша дитина правильно розвивається",
                      "description": "Щоб ваша дитина виросла здоровою і добре розвивалася,\n    привчайте її до певного розпорядку дня. Регулярне годування – основа режиму\n    немовляти. Годуйте новонародженого до 3-х місяців (включно) сім разів на добу\n    через 3 години. Після 3-х місячного віку переходьте на годування через 3,5\n    години (6 разів) з перервою вночі 6,5 годин. З 5-6-ти місячного віку годуєте\n    дитину п’ять разів на день через 4 години, з перервою на ніч – 8 годин.\n    Після ситного обіду новонароджена дитина має не спати близько півгодини,\n    двомісячна – близько години. Для сну дитині потрібне свіже і прохолодне\n    повітря, тому необхідно провітрювати його кімнату.\n    З трьохмісячного, до десятимісячного віку малюк повинен спати по 2 години\n    три рази на день, а з 10 місяців і до року – по 2-2,5 години два рази на\n    день.\n    Крім провітрювання, дитині необхідні свіже повітря і сонячне світло.\n    Вона повинна проводити на свіжому повітрі декілька годин, і поки вона не\n    може ходити, укладайте її спати вдень на свіжому повітрі – це зміцнить її\n    організм і застереже від захворювань .\n    Прогулянки починайте з двотижневого віку протягом 15-20 хвилин, поступово\n    подовжуючи час прогулянок до 1,5-2 годин.",
                      "published_at": "2022-01-24T15:28:06.797Z",
                      "created_at": "2022-01-24T15:18:06.802Z",
                      "updated_at": "2022-01-24T15:18:06.802Z",
                      "image": {
                        "url": "/uploads/article/image/15/2.png"
                      },
                      "category_id": 4,
                      "age": "18-24 місяці",
                      "subject": "Вакцинація"
                    },
                    {
                      "id": 16,
                      "title": "Чого очікувати у перші тижні з дитиною",
                      "description": "Щоб ваша дитина виросла здоровою і добре розвивалася,\n    привчайте її до певного розпорядку дня. Регулярне годування – основа режиму\n    немовляти. Годуйте новонародженого до 3-х місяців (включно) сім разів на добу\n    через 3 години. Після 3-х місячного віку переходьте на годування через 3,5\n    години (6 разів) з перервою вночі 6,5 годин. З 5-6-ти місячного віку годуєте\n    дитину п’ять разів на день через 4 години, з перервою на ніч – 8 годин.\n    Після ситного обіду новонароджена дитина має не спати близько півгодини,\n    двомісячна – близько години. Для сну дитині потрібне свіже і прохолодне\n    повітря, тому необхідно провітрювати його кімнату.\n    З трьохмісячного, до десятимісячного віку малюк повинен спати по 2 години\n    три рази на день, а з 10 місяців і до року – по 2-2,5 години два рази на\n    день.\n    Крім провітрювання, дитині необхідні свіже повітря і сонячне світло.\n    Вона повинна проводити на свіжому повітрі декілька годин, і поки вона не\n    може ходити, укладайте її спати вдень на свіжому повітрі – це зміцнить її\n    організм і застереже від захворювань .\n    Прогулянки починайте з двотижневого віку протягом 15-20 хвилин, поступово\n    подовжуючи час прогулянок до 1,5-2 годин.",
                      "published_at": "2022-01-24T15:28:06.833Z",
                      "created_at": "2022-01-24T15:18:06.839Z",
                      "updated_at": "2022-01-24T15:18:06.839Z",
                      "image": {
                        "url": "/uploads/article/image/16/4.png"
                      },
                      "category_id": 4,
                      "age": "4-5 роки",
                      "subject": "Купання"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  }
}