---
swagger: '2.0'
info:
  title: API V1
  version: v1
definitions:
  createArticle:
    type: object
    properties:
      data:
        type: object
        required:
        - title,
        - description,
        - category_id,
        - published_at,
        - image,
        - age,
        - subject
        properties:
          title:
            type: string
            example: title
          description:
            type: string
            example: this about article
          category_id:
            type: bigint
            example: '1'
          published_at:
            type: datetime
            example: Wed, 05 Jan 2022 13:13:08.710789000 UTC +00:00
          image:
            type: string
            example: "/uploads/article/image/23/4.png"
          age:
            type: string
            example: 0-3 mounth
          subject:
            type: string
            example: dream
paths:
  "/api/v1/categories/{id}":
    get:
      summary: Lists category articles
      tags:
      - category
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: lists articles
          schema:
            type: object
            properties:
              activities:
                type: array
                items:
                  properties:
                    title:
                      type: string
                    published_at:
                      type: datetime
                    image:
                      type: string
                  required:
                  - title,
                  - published_at,
                  - image
